---
version: "3"
services:
  postgres:
    image: postgres
  redis:
    image: redis
  hound:
    build: hound
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    env_file:
      - hound.env
      - hound.private.env
    environment:
      ENABLE_HTTPS: "no"
      NODE_ENV: "production"
      RAILS_ENV: "production"
      DATABASE_URL: "postgresql://postgres@postgres/hound"
      REDIS_URL: "redis://redis:6379/0"
  resque:
    build: hound
    depends_on:
      - postgres
      - redis
    env_file:
      - hound.env
      - hound.private.env
    environment:
      ENABLE_HTTPS: "no"
      NODE_ENV: "production"
      RAILS_ENV: "production"
      DATABASE_URL: "postgresql://postgres@postgres/hound"
      REDIS_URL: "redis://redis:6379/0"
      TERM_CHILD: "1"
      RESQUE_TERM_TIMEOUT: "8"
      QUEUE: high,medium,low
    entrypoint: ""
    command: bundle exec rake resque:work
  scheduler:
    build: hound
    depends_on:
      - postgres
      - redis
    env_file:
      - hound.env
      - hound.private.env
    environment:
      NODE_ENV: "production"
      RAILS_ENV: "production"
      DATABASE_URL: "postgresql://postgres@postgres/hound"
      REDIS_URL: "redis://redis:6379/0"
      TERM_CHILD: "1"
      RESQUE_TERM_TIMEOUT: "8"
      QUEUE: high,medium,low
    entrypoint: ""
    command: bundle exec rake resque:scheduler
  linters:
    build: hound-linters
    depends_on:
      - redis
    environment:
      RACK_ENV: "production"
      REDIS_URL: "redis://redis:6379/0"
  python:
    build: hound-python
    depends_on:
      - redis
    environment:
      REDIS_URL: "redis://redis:6379/0"
  remark:
    build: hound-remark
    depends_on:
      - redis
    environment:
      REDIS_URL: "redis://redis:6379/0"
