FROM ruby:2.3.1

RUN apt-get update && apt-get install -y --no-install-recommends \
    # For assets compilation
    nodejs \
    # Capybara-webkit deps
    dbus-1-dbg \
    libqt5webkit5-dev \
    qt5-default \
    xvfb \
    # Git
    git \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && dbus-uuidgen > /etc/machine-id

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

RUN mkdir -p /usr/src/app
RUN git clone https://github.com/houndci/hound /usr/src/app \
    && cd /usr/src/app \
    && git reset --hard 7746ba991d710f32b3f1ccae5bcaa0f4176d7265
WORKDIR /usr/src/app

RUN bundle install

CMD bundle exec rails s -b0.0.0.0
